substitutions:
  esp_board_name: firebeetle
  location: woonkamer
  static_ip: 192.168.1.121
  LD2410_pin: "GPIO27"
  sensors: "LD2410; Senseair"

  <<: !include common/standard_naming_substitutions.yaml

esphome:
  name: ${system_name}
  comment: "${device_description}"
  friendly_name: ${friendly_name}

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

esp32:
  board: firebeetle32
  framework:
    type: arduino

# Enable logging
logger:
  level: warn
  baud_rate: 0  # no logging to uart

# Enable Home Assistant API
api:
  reboot_timeout: 60min

ota:
  platform: esphome
  password: !secret ota_password_firebeetle

esp32_ble_tracker:
  scan_parameters:
    duration: 60s
    active: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Firebeetle"
    password: "TzZW1Z3JC0cW"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: ${static_ip}
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.2.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0


captive_portal:

#Occupancy sensor
binary_sensor:
  - <<: !include common/ld2410_binary_sensor.yaml
#   - platform: gpio
#     pin: ${LD2410_pin}
#     name: "${friendly_name} LD2410 presence (esphome)"
#     device_class: presence

sensor:
  - platform: senseair
    co2:
      name: "SenseAir CO2 Value"
    update_interval: 60s

  - platform: uptime
    name: "Firebeetle uptime Sensor"

  - platform: wifi_signal
    name: "Firebeetle WiFi Signal"
    update_interval: 60s

  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:33:B8:6F
    temperature:
      name: "Mi Temperature 1"
    humidity:
      name: "Mi Humidity 1"
    battery_level:
      name: "Mi Battery Level 1"
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:35:9A:CA
    temperature:
      name: "Mi Temperature 2"
    humidity:
      name: "Mi Humidity 2"
    battery_level:
      name: "Mi Battery Level 2"
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:38:57:36
    temperature:
      name: "Mi Temperature 3"
    humidity:
      name: "Mi Humidity 3"
    battery_level:
      name: "Mi Battery Level 3"
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:0E:09:4D
    temperature:
      name: "Mi Temperature 4"
    humidity:
      name: "Mi Humidity 4"
    battery_level:
      name: "Mi Battery Level 4"
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:0B:17:B9
    temperature:
      name: "Mi Temperature 5"
    humidity:
      name: "Mi Humidity 5"
    battery_level:
      name: "Mi Battery Level 5"
  - platform: pvvx_mithermometer  # Studeerkamer
    mac_address: A4:C1:38:FD:3C:03
    temperature:
      name: "Mi Temperature 6"
      id: mi_6_temperature
    humidity:
      name: "Mi Humidity 6"
      id: mi_6_humidity
    battery_level:
      name: "Mi Battery Level 6"
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:9B:DB:F6
    temperature:
      name: "Mi Temperature 7"
    humidity:
      name: "Mi Humidity 7"
    battery_level:
      name: "Mi Battery Level 7"
  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:72:BD:D5
    temperature:
      name: "Mi Temperature 8"
    humidity:
      name: "Mi Humidity 8"
    battery_level:
      name: "Mi Battery Level 8"

#   - platform: dht
#     pin: 25
#     temperature:
#       name: "Living Room Temperature"
#     humidity:
#       name: "Living Room Humidity"
#     update_interval: 1s

time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 0
        hours: 4
        days_of_week: MON-SUN
        then:
           - switch.toggle: restart_switch
switch:
  - platform: restart
    name: "test_temperature Restart"
    id: restart_switch
