substitutions:
  name: home-assistant-voice-09bcf1
  friendly_name: Home Assistant Voice 09bcf1
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  # encryption:
  #   key: w2fNJqARVCThwYTxKvW4uazfSKpJZbGFB3QkGk8CRnU=

# This is how I personally tune my voice assistant, you may have to test a few values for the 4 parameters above
voice_assistant:
  noise_suppression_level: 3
  auto_gain: 30dBFS
  volume_multiplier: 8
  # vad_threshold: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
