esphome:
  name: wemos-dev2-presence
  comment: LD2410 presence detection radar on Wemos s2 mini
  friendly_name: Wemos s2 mini with LD2410
  # name_add_mac_suffix: True
  # platformio_options:
    # board_build.flash_mode: dio
    # board_build.extra_flags:
      # - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: lolin_s2_mini

improv_serial:

logger:
  # hardware_uart: uart0
  level: VERY_VERBOSE

api:
  encryption:
    key: !secret ha_api_wemos_s2_dev2

ota:
  password: "X4FSi0Q1Gm8bmQ1eUzZEaFoKsxC9CkyV"
  id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  manual_ip:
    # Set this to the IP of the ESP. router should not lease IP's above 150
    static_ip: 192.168.2.133
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.2.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  power_save_mode: NONE
  ap:
    ssid: "WemosLD2410"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80

sensor:
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 180s
    entity_category: "diagnostic"
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 600s
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 600s
    entity_category: "diagnostic"

#Occupancy sensor
binary_sensor:
  - platform: gpio
    pin: 16
    name: Wemos-dev2-LD2410
    device_class: presence

time:
  - platform: homeassistant

light:
  - platform: status_led
    name: sys_status
    pin: GPIO15
    internal: True
    restore_mode: ALWAYS_OFF
