esphome:
  name: wemost-s2-mini-1
  friendly_name: wemost s2 mini 1

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zi22R7hiJ+BOWeqE7XvhIrpkC80nSHQaenk0GMoGMXg="

ota:
  password: "c7634ea8a3e412de028854d656602c98"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemost-S2-Mini-1A"
    password: "ftxLXWPUoyYr"
  
  manual_ip:
    # Set this to the IP of the ESP. router should not lease IP's above 150
    static_ip: 192.168.2.132
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.2.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

captive_portal:

sensor:
  - platform: uptime
    name: "wemos uptime Sensor"

  - platform: wifi_signal
    name: "wemos WiFi Signal"
    update_interval: 60s
