substitutions:
  esp_boardname: name-and-type-of-the-board
  location: location-of-the-sensor-in-the-house
  system_name: "esphome-${location}" #name-of-device-preferably-location
  friendly_name: ${location} # <usually CAML case version of the hostname i.e Living Room>
  device_description: "${esp-boardname} in ${location}"
  static_ip: 192.168.2.1
  LD2410_pin: "16"

esphome:
  name: ${system_name}
  comment: "${device_description}"
  friendly_name: ${friendly_name}
  # name_add_mac_suffix: True
  # platformio_options:
    # board_build.flash_mode: dio
    # board_build.extra_flags:
      # - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: lolin_s2_mini

improv_serial:

logger:
#   baud_rate: 0
  # level: VERY_VERBOSE
  level: INFO

api:
  encryption:
    key: !secret ha_api_studeerkamer_wemos_s2_mini

ota:
  password: "X4FSi0Q1Gm8bmQ1eUzZEaFoKsxC9CkyV"
  id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  manual_ip:
    # Set this to the IP of the ESP. router should not lease IP's above 150
    static_ip: ${static_ip}
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.2.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  power_save_mode: NONE
  ap:
    ssid: ${system_name}
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80

# TODO: Make these sensor namings more generic
sensor:
  - platform: template
    id: sys_esp_temperature
    name: "${friendly_name} ESP Temperature (esphome)"
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 180s
    entity_category: "diagnostic"
  - platform: uptime
    name: "${friendly_name} Node Uptime (esphome)"
    id: sys_uptime
    update_interval: 600s
  - platform: wifi_signal
    name: "${friendly_name} RSSI (esphome)"
    id: wifi_signal_db
    update_interval: 600s
    entity_category: "diagnostic"

#Occupancy sensor
binary_sensor:
  - platform: gpio
    pin: ${LD2410_pin}
    name: "${friendly_name} LD2410 presence (esphome)"
    device_class: presence

time:
  - platform: homeassistant

light:
  - platform: status_led
    name: sys_status
    pin: GPIO15
    internal: True
    restore_mode: ALWAYS_OFF
