# zie in woonkamer-dressoir-firebeetle.yaml voor werkend gebruik van packages
packages:
  <<:
    - !include_dir_named ../components/common
    - !include ../components/sensors/default_onboard_esp_sensors.yaml
    - !include ../components/sensors/ld2410_binary_sensor.yaml
    - !include ../boards/wemos-s2-mini.yaml

substitutions:
  esp_board_name: name-and-type-of-the-board
  location: location-of-the-sensor-in-the-house
  LD2410_pin: "16"

  <<: !include ../substitutions/standard_naming_substitutions.yaml

