substitutions:
  esp_board_name: wemos-s2-mini
  location: studeerkamer
  sensors: "LD2410"
  LD2410_pin: "16"
  <<: !include ../substitutions/standard_naming_substitutions.yaml

# zie in woonkamer-dressoir-firebeetle.yaml voor werkend gebruik van packages
packages:
  common: !include_dir_named ../components/common
  board: !include ../boards/wemos-s2-mini.yaml

# zie in woonkamer-dressoir-firebeetle.yaml voor werkend gebruik van packages,
# hierdoor is onderstaande sensor block niet meer nodig
sensor:
  <<: !include ../components/sensors/default_onboard_esp_sensors.yaml
binary_sensor:
  <<: !include ../components/sensors/ld2410_binary_sensor.yaml


