# sensors that are always available in ESP
sensor:
  - platform: internal_temperature
    id: sys_esp_temperature
    name: "${friendly_name} internal temperature (esphome)"
  - platform: uptime
    name: "${friendly_name} Node Uptime (esphome)"
    id: sys_uptime
    update_interval: 600s
  - platform: wifi_signal
    name: "${friendly_name} RSSI (esphome)"
    id: wifi_signal_db
    update_interval: 600s
    entity_category: "diagnostic"