#Occupancy sensor, include it in a binary_sensor: block in your main yaml file
binary_sensor:
  - platform: gpio
    pin: ${LD2410_pin}
    name: "${friendly_name} LD2410 presence (esphome)"
    device_class: presence
